version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - voting-network
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: votes
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - voting-network
    restart: unless-stopped

  vote:
    build: ./vote
    container_name: vote
    ports:
      - "5000:80"
    networks:
      - voting-network
    depends_on:
      - redis
    restart: unless-stopped

  result:
    build: ./result
    container_name: result
    ports:
      - "5001:80"
    networks:
      - voting-network
    depends_on:
      - postgres
    restart: unless-stopped

  worker:
    build: ./worker
    container_name: worker
    networks:
      - voting-network
    depends_on:
      - redis
      - postgres
    restart: unless-stopped

volumes:
  postgres-data:
  redis-data:

networks:
  voting-network:
    driver: bridge
